// ─────────────────────────────────────────────────────────────
//  Brand Book Schema
//  Every user brand book follows this structure, generated by
//  the PostPal AI onboarding agent. Mirrors Brand Guide v2.
// ─────────────────────────────────────────────────────────────

import { z } from "zod";
import type {
  ComplimentChoice,
  DressCodeChoice,
  GreetingChoice,
} from "@/lib/onboarding-choices";

export type { ComplimentChoice, DressCodeChoice, GreetingChoice } from "@/lib/onboarding-choices";

// ── 01 At a Glance ──────────────────────────────────────────

export interface BrandGlance {
  story: string;
  whatItIs: string;
  howItWorks: string;
  whoItsFor: string;
  howWeSound: string;
}

// ── 02 The Mark ─────────────────────────────────────────────

export interface LogoVariant {
  label: string;
  url: string;
  surface: "light" | "dark" | "accent";
}

export interface BrandMark {
  variants: LogoVariant[];
  minSizePx: number;
  clearSpace: string;
  donts: string[];
}

// ── 03 Color ────────────────────────────────────────────────

export interface BrandColor {
  name: string;
  hex: string;
  role: "primary-dark" | "primary-light" | "accent";
  rgb: string;
  cmyk?: string;
  pantone?: string;
}

export interface BrandPalette {
  ink: BrandColor;
  bone: BrandColor;
  signal: BrandColor;
  muted: BrandColor;
  proportion: { ink: number; bone: number; signal: number; muted: number };
}

// ── 04 Typography ───────────────────────────────────────────

export interface TypeFace {
  family: string;
  role: "display" | "body";
  weights: string[];
  letterSpacing: string;
  googleFontsUrl?: string;
}

export interface TypeScaleEntry {
  name: string;
  face: "display" | "body";
  size: string;
  weight: string;
  tracking: string;
  sample: string;
}

export interface BrandTypography {
  display: TypeFace;
  body: TypeFace;
  scale: TypeScaleEntry[];
}

// ── 05 Voice ────────────────────────────────────────────────

export interface VoiceTrait {
  name: string;
  description: string;
}

export interface Tagline {
  quiet: string;
  loud: string;
}

export interface BrandVoice {
  hero: string;
  weSay: string[];
  weDontSay: string[];
  always: string;
  sometimes: string;
  never: string;
  italicRule: string;
  traits: VoiceTrait[];
  taglines: Tagline[];
}

// ── 06 In Use ───────────────────────────────────────────────

export interface PostTemplate {
  name: string;
  surface: "light" | "dark";
  kicker: string;
  headlinePattern: string;
  accentWord: string;
  footerLeft: string;
  footerRight: string;
  stamp?: string;
}

export interface BrandApplications {
  postTemplates: PostTemplate[];
  onboardingChat: {
    agentName: string;
    greeting: string;
    sampleExchange: { role: "agent" | "user"; text: string }[];
  };
  stationery?: {
    frontSurface: "light" | "dark";
    backSurface: "light" | "dark";
    stock?: string;
    finish?: string;
  };
}

// ── 07 Colophon ─────────────────────────────────────────────

export interface BrandColophon {
  version: string;
  issuedDate: string;
  contact: string;
}

// ── Agent Identity ──────────────────────────────────────────

import type { IndustryId } from "@/lib/industries";
import type { CuratedPaletteId } from "@/lib/color-registry";

export interface AgentIdentity {
  name: string;
  /**
   * Display title (e.g. "Realtor", "Pastry Chef", "Personal Trainer").
   * Legacy: was hardcoded to "Realtor" by the generator. New code sets
   * this from OnboardingAnswers.profession when available.
   */
  title: string;
  /**
   * Legacy alias for `company`. Kept for backward compat with existing
   * brand books in localStorage. New code reads `company ?? brokerage`.
   */
  brokerage?: string;
  /** Preferred over `brokerage` going forward — vertical-agnostic. */
  company?: string;
  location: string;
  markets: string[];
  phone?: string;
  email?: string;
  website?: string;
  social?: string;
  target: string;
  experience?: string;
  headshot?: string;

  // ── New (Phase 1 — onboarding generalization) ─────────────
  /** Selected industry vertical from the taxonomy in src/lib/industries.ts. */
  industry?: IndustryId;
  /** Free-text profession label, typed by the user. */
  profession?: string;
  /** 1–2 sentence "why we do this" — feeds glance.story + voice.hero. */
  mission?: string;
  /** Curated palette from color-registry — never AI-invented hex codes. */
  paletteId?: CuratedPaletteId;
}

// ── Photography ─────────────────────────────────────────────

export interface PhotographyStyle {
  description: string;
  principles: { name: string; description: string }[];
}

// ── Content Strategy ────────────────────────────────────────

export interface ContentPillar {
  name: string;
  description: string;
  frequency: "daily" | "weekly" | "biweekly" | "monthly";
}

// ═══════════════════════════════════════════════════════════
//  The Brand Book
// ═══════════════════════════════════════════════════════════

export interface BrandBook {
  id: string;
  userId: string;
  createdAt: string;
  updatedAt: string;
  status: "onboarding" | "draft" | "active";

  // 00 — Identity
  identity: AgentIdentity;

  // 01 — At a Glance
  glance: BrandGlance;

  // 02 — The Mark
  mark: BrandMark;

  // 03 — Color
  palette: BrandPalette;

  // 04 — Typography
  typography: BrandTypography;

  // 05 — Voice
  voice: BrandVoice;

  // 06 — In Use
  applications: BrandApplications;

  // Photography direction
  photography: PhotographyStyle;

  // Content pillars
  pillars: ContentPillar[];

  // 07 — Colophon
  colophon: BrandColophon;

  /** Midjourney/Kling-ready lifestyle merch prompts (packaging, coaster, apparel). */
  collateralPrompts?: string[];
}

// ═══════════════════════════════════════════════════════════
//  Onboarding — what the agent collects
// ═══════════════════════════════════════════════════════════

export interface OnboardingAnswers {
  name: string;
  /** Business / venue / practice name (preferred). */
  company?: string;
  /** @deprecated Use `company`. Kept for legacy flows. */
  brokerage?: string;
  location: string;
  markets: string[];
  targetClient: string;
  personalityTraits: string[];
  experience?: string;
  phone?: string;
  email?: string;
  website?: string;
  social?: string;

  // Uploaded assets
  logo?: string;
  headshot?: string;
  brandColors?: string[];
  fontPairing?: string;

  // Preferences
  tonePreference: "warm" | "professional" | "playful" | "authoritative";
  contentFocus: string[];

  // ── Phase 1 (post-beta refactor) ──────────────────────────
  // Loose at intake (wizard may free-text "salon" before the picker step
  // exists); generator narrows to IndustryId when building AgentIdentity.
  // Accepts IndustryId values from src/lib/industries.ts when typed.
  industry?: string;
  /** Free-text profession label ("Realtor", "Pastry Chef"). */
  profession?: string;
  /** 1–2 sentence "why we do this", in the user's own words. */
  mission?: string;
  /** 1–3 short writing samples — feeds Phase 3 voice synthesis. */
  voiceSamples?: string[];
  /** ≤3 examples of voice they DON'T want to sound like (text snippets). */
  antiVoice?: string[];
  /** ≤3 URLs or @handles they admire visually (optional v1 reference only). */
  visualRefs?: string[];

  // ── Behavioral onboarding (plain-English, no jargon) ───────
  /** "If your business had a dress code…" → curated palette + visual vibe. */
  dressCode?: DressCodeChoice;
  /** "A new customer walks through the door…" → weSay / weDontSay tone. */
  greeting?: GreetingChoice;
  /** "Best 5-star review…" → hero positioning. */
  compliment?: ComplimentChoice;
}

// ═══════════════════════════════════════════════════════════
//  AI structured output (Vercel AI SDK + Zod)
// ═══════════════════════════════════════════════════════════

export const curatedPaletteIdSchema = z.enum([
  "sharp-professional",
  "smart-casual",
  "jeans-tshirt",
  "boots-flannel",
]);

/** Strict schema for `generateObject` — voice + paletteId only (no free-form colors). */
export const brandVoiceAiSchema = z.object({
  paletteId: curatedPaletteIdSchema.describe(
    "Pick exactly one curated palette ID that matches the user's Dress Code and industry vibe. Never invent hex codes or color names — only these four IDs exist.",
  ),
  hero: z
    .string()
    .min(12)
    .max(320)
    .describe(
      "One-sentence positioning statement anchored in the user's Compliment choice (best 5-star review theme). Industry-native language only.",
    ),
  weSay: z
    .array(z.string().min(8).max(280))
    .min(3)
    .max(5)
    .describe(
      "Example social lines shaped by the user's Greeting — how they actually talk when someone walks in.",
    ),
  weDontSay: z
    .array(z.string().min(8).max(280))
    .min(3)
    .max(6)
    .describe(
      "Off-brand lines — include tones that contradict the Greeting and forbidden industry words.",
    ),
  traits: z
    .array(z.string().min(2).max(80))
    .min(3)
    .max(5)
    .describe("Short voice trait labels grounded in Dress Code + Greeting, not generic adjectives."),
  collateralPrompts: z
    .array(z.string().min(40).max(2000))
    .length(3)
    .describe(
      "Exactly 3 detailed image-generation prompts (Midjourney/Kling). Index 0: custom packaging/bags/boxes. Index 1: branded coaster or physical touchpoint on textured surface. Index 2: modern staff apparel. No paper menu systems.",
    ),
});

export type BrandVoiceAiOutput = z.infer<typeof brandVoiceAiSchema>;

// ═══════════════════════════════════════════════════════════
//  Defaults — thepostpal's own brand values
//  Used as the chrome around every user's generated content
// ═══════════════════════════════════════════════════════════

export const POSTPAL_BRAND = {
  ink: "#0F0F0F",
  bone: "#F2EEE6",
  bone2: "#E9E4D8",
  signal: "#1E3A8A",
  muted: "#807868",
  displayFont: "Quicksand",
  bodyFont: "DM Sans",
} as const;

// ═══════════════════════════════════════════════════════════
//  Helper — build AI system prompt from a brand book
// ═══════════════════════════════════════════════════════════

export function buildBrandPrompt(book: BrandBook): string {
  const { identity: id, glance, palette, typography, voice, photography, pillars } = book;

  return `## Brand Identity
- Name: ${id.name}
- Title: ${id.title}${id.brokerage ? ` at ${id.brokerage}` : ""}
- Location: ${id.location}
- Markets: ${id.markets.join(", ")}
- Target: ${id.target}
${id.experience ? `- Experience: ${id.experience}` : ""}
${id.phone ? `- Phone: ${id.phone}` : ""}
${id.email ? `- Email: ${id.email}` : ""}
${id.website ? `- Website: ${id.website}` : ""}

## Brand Essence
${glance.story}

What it is: ${glance.whatItIs}
Who it's for: ${glance.whoItsFor}
How we sound: ${glance.howWeSound}

## Color Palette
- Ink: ${palette.ink.name} (${palette.ink.hex}) — dark surface, ${palette.proportion.ink}%
- Bone: ${palette.bone.name} (${palette.bone.hex}) — light surface, ${palette.proportion.bone}%
- Signal: ${palette.signal.name} (${palette.signal.hex}) — accent, ${palette.proportion.signal}%
- Muted: ${palette.muted.name} (${palette.muted.hex}) — secondary neutral, ${palette.proportion.muted}%

## Typography
- Display: ${typography.display.family}
- Body: ${typography.body.family}

## Voice
${voice.hero}

We say:
${voice.weSay.map((s) => `- "${s}"`).join("\n")}

We don't say:
${voice.weDontSay.map((s) => `- "${s}"`).join("\n")}

Always: ${voice.always}
Sometimes: ${voice.sometimes}
Never: ${voice.never}
${voice.italicRule ? `\nItalic rule: ${voice.italicRule}` : ""}

## Photography
${photography.description}
${photography.principles.map((p) => `- ${p.name}: ${p.description}`).join("\n")}

## Content Pillars
${pillars.map((p) => `- ${p.name} (${p.frequency}): ${p.description}`).join("\n")}`;
}
