export interface Template {
  id: string;
  name: string;
  pillar: string;
  description: string;
  width: number;
  height: number;
  bgType: "navy" | "ivory" | "photo-overlay" | "photo-fullbleed" | "split";
  layout: "centered" | "left-aligned" | "bottom-text" | "split-header";
  hasPhotoSlot: boolean;
  preview?: string;
  fields: TemplateField[];
}

export interface TemplateField {
  id: string;
  label: string;
  type: "eyebrow" | "headline" | "body" | "cta" | "list" | "date" | "location";
  defaultValue: string;
  maxLength?: number;
}

export const templates: Template[] = [
  {
    id: "navy-text",
    name: "Market Clarity Card",
    pillar: "Market Clarity",
    description: "Navy background with arch frame. For market updates and strategy.",
    width: 1080,
    height: 1080,
    bgType: "navy",
    layout: "centered",
    hasPhotoSlot: true,
    preview: "/previews/market-clarity.png",
    fields: [
      { id: "eyebrow", label: "Category", type: "eyebrow", defaultValue: "MARKET CLARITY", maxLength: 30 },
      { id: "headline", label: "Headline", type: "headline", defaultValue: "Your Headline Here", maxLength: 60 },
      { id: "body", label: "Body Text", type: "body", defaultValue: "Add your market insight or update here.", maxLength: 200 },
    ],
  },
  {
    id: "ivory-checklist",
    name: "Tips & Checklist Card",
    pillar: "Buyer / Seller Tips",
    description: "Ivory background with list format. For buyer tips and seller checklists.",
    width: 1080,
    height: 1080,
    bgType: "ivory",
    layout: "left-aligned",
    hasPhotoSlot: true,
    preview: "/previews/tips-checklist.png",
    fields: [
      { id: "eyebrow", label: "Category", type: "eyebrow", defaultValue: "BUYER CONFIDENCE", maxLength: 30 },
      { id: "headline", label: "Headline", type: "headline", defaultValue: "3 Questions Before Your First Tour", maxLength: 60 },
      { id: "list", label: "List Items (one per line)", type: "list", defaultValue: "How do you want your daily routine to feel?\nWhat is your timeline, and how does financing fit?\nIs the neighborhood the priority, or are you flexible?" },
      { id: "cta", label: "Call to Action", type: "cta", defaultValue: "Message me to get started", maxLength: 50 },
    ],
  },
  {
    id: "photo-overlay",
    name: "Photo Overlay Card",
    pillar: "Neighborhood / Lifestyle",
    description: "Your photo with gradient overlay and white text. For neighborhoods and listings.",
    width: 1080,
    height: 1350,
    bgType: "photo-overlay",
    layout: "bottom-text",
    hasPhotoSlot: true,
    preview: "/previews/photo-overlay.png",
    fields: [
      { id: "eyebrow", label: "Category", type: "eyebrow", defaultValue: "NEIGHBORHOOD GUIDE", maxLength: 30 },
      { id: "headline", label: "Headline", type: "headline", defaultValue: "A Saturday in Wildwood", maxLength: 50 },
      { id: "body", label: "Subtitle", type: "body", defaultValue: "Trails, open space, and a slower pace.", maxLength: 150 },
    ],
  },
  {
    id: "quote-personal",
    name: "Quote & Personal Card",
    pillar: "Angie Personal",
    description: "Photo background with centered serif headline. For personal posts and values.",
    width: 1080,
    height: 1080,
    bgType: "photo-overlay",
    layout: "centered",
    hasPhotoSlot: true,
    preview: "/previews/quote-personal.png",
    fields: [
      { id: "headline", label: "Quote / Headline", type: "headline", defaultValue: "It's Never Just About the House.", maxLength: 60 },
    ],
  },
  {
    id: "event-spotlight",
    name: "Event Spotlight Card",
    pillar: "Local Life",
    description: "Navy card with photo top. For local events and festivals.",
    width: 1080,
    height: 1350,
    bgType: "split",
    layout: "split-header",
    hasPhotoSlot: true,
    preview: "/previews/event-spotlight.png",
    fields: [
      { id: "date", label: "Event Date", type: "date", defaultValue: "JULY 3 - 4, 2026", maxLength: 30 },
      { id: "headline", label: "Event Name", type: "headline", defaultValue: "Celebrate Saint Louis Festival", maxLength: 50 },
      { id: "body", label: "Description", type: "body", defaultValue: "Live performances, family activities, and fireworks.", maxLength: 200 },
      { id: "location", label: "Location", type: "location", defaultValue: "DOWNTOWN ST. LOUIS", maxLength: 40 },
    ],
  },
  {
    id: "neighborhood-guide",
    name: "Neighborhood Guide Card",
    pillar: "Neighborhood Life",
    description: "Photo top with arch mask, ivory content below. For neighborhood spotlights.",
    width: 1080,
    height: 1350,
    bgType: "ivory",
    layout: "split-header",
    hasPhotoSlot: true,
    fields: [
      { id: "eyebrow", label: "Category", type: "eyebrow", defaultValue: "NEIGHBORHOOD GUIDE", maxLength: 30 },
      { id: "headline", label: "Headline", type: "headline", defaultValue: "Is Chesterfield the Right Fit?", maxLength: 50 },
    ],
  },
  {
    id: "story-event",
    name: "Story Template",
    pillar: "Stories / Reels",
    description: "Full-screen vertical story with gradient overlay. For quick announcements.",
    width: 1080,
    height: 1920,
    bgType: "photo-overlay",
    layout: "bottom-text",
    hasPhotoSlot: true,
    fields: [
      { id: "eyebrow", label: "Label", type: "eyebrow", defaultValue: "THIS WEEKEND", maxLength: 20 },
      { id: "headline", label: "Headline", type: "headline", defaultValue: "Festival of Little Hills", maxLength: 40 },
      { id: "cta", label: "CTA Text", type: "cta", defaultValue: "Swipe up for details", maxLength: 30 },
    ],
  },
  {
    id: "market-stats",
    name: "Market Stats Card",
    pillar: "Market Clarity",
    description: "Split layout with navy header and ivory stats. For data-driven posts.",
    width: 1080,
    height: 1080,
    bgType: "split",
    layout: "split-header",
    hasPhotoSlot: true,
    fields: [
      { id: "eyebrow", label: "Category", type: "eyebrow", defaultValue: "WEST COUNTY MARKET", maxLength: 30 },
      { id: "headline", label: "Headline", type: "headline", defaultValue: "Mid-Year Snapshot", maxLength: 40 },
      { id: "list", label: "Stats (format: number | description, one per line)", type: "list", defaultValue: "12 | Average days on market for well-priced homes\n97% | List-to-sale price ratio\n3.2x | More showings for staged listings" },
    ],
  },
  {
    id: "lifestyle-fullbleed",
    name: "Lifestyle Full Bleed",
    pillar: "Home + Lifestyle",
    description: "Full photo with navy text bar at bottom. For seasonal and lifestyle content.",
    width: 1080,
    height: 1080,
    bgType: "photo-fullbleed",
    layout: "bottom-text",
    hasPhotoSlot: true,
    fields: [
      { id: "headline", label: "Headline", type: "headline", defaultValue: "Happy First Day of Summer", maxLength: 40 },
    ],
  },

  // ── New Listing ──────────────────────────────────────────
  {
    id: "new-listing-photo",
    name: "New Listing Photo",
    pillar: "New Listing",
    description: "Photo overlay with listing details. For announcing new properties on the market.",
    width: 1080,
    height: 1350,
    bgType: "photo-overlay",
    layout: "bottom-text",
    hasPhotoSlot: true,
    fields: [
      { id: "eyebrow", label: "Label", type: "eyebrow", defaultValue: "NEW LISTING", maxLength: 20 },
      { id: "headline", label: "Address", type: "headline", defaultValue: "123 Main Street, Chesterfield", maxLength: 60 },
      { id: "body", label: "Details", type: "body", defaultValue: "4 BD · 3 BA · 2,800 SF", maxLength: 80 },
      { id: "cta", label: "Call to Action", type: "cta", defaultValue: "Schedule a private showing", maxLength: 50 },
    ],
  },
  {
    id: "new-listing-card",
    name: "New Listing Card",
    pillar: "New Listing",
    description: "Navy card with photo header for new listing announcements.",
    width: 1080,
    height: 1080,
    bgType: "split",
    layout: "split-header",
    hasPhotoSlot: true,
    fields: [
      { id: "eyebrow", label: "Label", type: "eyebrow", defaultValue: "JUST LISTED", maxLength: 20 },
      { id: "headline", label: "Address", type: "headline", defaultValue: "456 Elm Court, Wildwood", maxLength: 60 },
      { id: "body", label: "Property Description", type: "body", defaultValue: "Stunning 5-bedroom on a quiet cul-de-sac with resort-style backyard.", maxLength: 200 },
      { id: "list", label: "Details (one per line)", type: "list", defaultValue: "5 Bedrooms · 4 Bathrooms\n3,400 Square Feet\nListed at $625,000" },
    ],
  },

  // ── Just Sold ────────────────────────────────────────────
  {
    id: "just-sold-photo",
    name: "Just Sold Photo",
    pillar: "Just Sold",
    description: "Photo overlay celebrating a closed sale. For sharing recent closings.",
    width: 1080,
    height: 1350,
    bgType: "photo-overlay",
    layout: "bottom-text",
    hasPhotoSlot: true,
    fields: [
      { id: "eyebrow", label: "Label", type: "eyebrow", defaultValue: "JUST SOLD", maxLength: 20 },
      { id: "headline", label: "Address", type: "headline", defaultValue: "789 Oak Lane, Kirkwood", maxLength: 60 },
      { id: "body", label: "Details", type: "body", defaultValue: "Closed in 5 days · Over asking price", maxLength: 100 },
    ],
  },
  {
    id: "just-sold-card",
    name: "Just Sold Card",
    pillar: "Just Sold",
    description: "Navy celebration card for sharing a sold property with details.",
    width: 1080,
    height: 1080,
    bgType: "navy",
    layout: "centered",
    hasPhotoSlot: true,
    fields: [
      { id: "eyebrow", label: "Label", type: "eyebrow", defaultValue: "SOLD", maxLength: 20 },
      { id: "headline", label: "Address", type: "headline", defaultValue: "Congratulations to My Buyers!", maxLength: 60 },
      { id: "body", label: "Message", type: "body", defaultValue: "Another family found their perfect home. Grateful to be part of the journey.", maxLength: 200 },
    ],
  },

  // ── Holiday Templates ────────────────────────────────────
  {
    id: "holiday-memorial-day",
    name: "Memorial Day",
    pillar: "Holiday",
    description: "Memorial Day tribute post. Red, white, and blue themed.",
    width: 1080,
    height: 1080,
    bgType: "photo-overlay",
    layout: "centered",
    hasPhotoSlot: true,
    fields: [
      { id: "eyebrow", label: "Label", type: "eyebrow", defaultValue: "MEMORIAL DAY", maxLength: 20 },
      { id: "headline", label: "Headline", type: "headline", defaultValue: "Honoring Those Who Served", maxLength: 50 },
      { id: "body", label: "Message", type: "body", defaultValue: "Remembering the brave men and women who gave everything.", maxLength: 150 },
    ],
  },
  {
    id: "holiday-fourth-july",
    name: "Fourth of July",
    pillar: "Holiday",
    description: "Independence Day celebration post with festive energy.",
    width: 1080,
    height: 1080,
    bgType: "photo-overlay",
    layout: "centered",
    hasPhotoSlot: true,
    fields: [
      { id: "eyebrow", label: "Label", type: "eyebrow", defaultValue: "HAPPY 4TH OF JULY", maxLength: 25 },
      { id: "headline", label: "Headline", type: "headline", defaultValue: "Celebrate Freedom", maxLength: 40 },
      { id: "body", label: "Message", type: "body", defaultValue: "Wishing you a safe and happy Independence Day!", maxLength: 150 },
    ],
  },
  {
    id: "holiday-labor-day",
    name: "Labor Day",
    pillar: "Holiday",
    description: "Labor Day post honoring the workforce and the last days of summer.",
    width: 1080,
    height: 1080,
    bgType: "photo-overlay",
    layout: "centered",
    hasPhotoSlot: true,
    fields: [
      { id: "eyebrow", label: "Label", type: "eyebrow", defaultValue: "LABOR DAY", maxLength: 20 },
      { id: "headline", label: "Headline", type: "headline", defaultValue: "Cheers to Hard Work", maxLength: 40 },
      { id: "body", label: "Message", type: "body", defaultValue: "Enjoy the long weekend — you've earned it.", maxLength: 150 },
    ],
  },
  {
    id: "holiday-halloween",
    name: "Halloween",
    pillar: "Holiday",
    description: "Halloween themed post with spooky seasonal spirit.",
    width: 1080,
    height: 1080,
    bgType: "photo-overlay",
    layout: "centered",
    hasPhotoSlot: true,
    fields: [
      { id: "eyebrow", label: "Label", type: "eyebrow", defaultValue: "HAPPY HALLOWEEN", maxLength: 25 },
      { id: "headline", label: "Headline", type: "headline", defaultValue: "Trick or Treat!", maxLength: 40 },
      { id: "body", label: "Message", type: "body", defaultValue: "Wishing you a fun and spooky evening in the neighborhood.", maxLength: 150 },
    ],
  },
  {
    id: "holiday-thanksgiving",
    name: "Thanksgiving",
    pillar: "Holiday",
    description: "Thanksgiving gratitude post with warm, inviting tone.",
    width: 1080,
    height: 1080,
    bgType: "photo-overlay",
    layout: "centered",
    hasPhotoSlot: true,
    fields: [
      { id: "eyebrow", label: "Label", type: "eyebrow", defaultValue: "HAPPY THANKSGIVING", maxLength: 25 },
      { id: "headline", label: "Headline", type: "headline", defaultValue: "Grateful for Home", maxLength: 40 },
      { id: "body", label: "Message", type: "body", defaultValue: "Thankful for the families I've helped find their place to gather.", maxLength: 150 },
    ],
  },
  {
    id: "holiday-christmas",
    name: "Christmas",
    pillar: "Holiday",
    description: "Christmas holiday post with festive and warm messaging.",
    width: 1080,
    height: 1080,
    bgType: "photo-overlay",
    layout: "centered",
    hasPhotoSlot: true,
    fields: [
      { id: "eyebrow", label: "Label", type: "eyebrow", defaultValue: "MERRY CHRISTMAS", maxLength: 25 },
      { id: "headline", label: "Headline", type: "headline", defaultValue: "There's No Place Like Home", maxLength: 50 },
      { id: "body", label: "Message", type: "body", defaultValue: "Wishing you warmth, joy, and time with the ones you love.", maxLength: 150 },
    ],
  },

  // ── First Day of Season ──────────────────────────────────
  {
    id: "season-spring",
    name: "First Day of Spring",
    pillar: "Seasonal",
    description: "Welcome spring with fresh, bright energy. Great for engagement posts.",
    width: 1080,
    height: 1080,
    bgType: "photo-fullbleed",
    layout: "bottom-text",
    hasPhotoSlot: true,
    fields: [
      { id: "headline", label: "Headline", type: "headline", defaultValue: "Happy First Day of Spring", maxLength: 40 },
      { id: "body", label: "Message", type: "body", defaultValue: "New blooms, fresh starts, and the best time to list.", maxLength: 100 },
    ],
  },
  {
    id: "season-summer",
    name: "First Day of Summer",
    pillar: "Seasonal",
    description: "Kick off summer with warm, vibrant content. Perfect for lifestyle posts.",
    width: 1080,
    height: 1080,
    bgType: "photo-fullbleed",
    layout: "bottom-text",
    hasPhotoSlot: true,
    fields: [
      { id: "headline", label: "Headline", type: "headline", defaultValue: "Happy First Day of Summer", maxLength: 40 },
      { id: "body", label: "Message", type: "body", defaultValue: "Long days, warm nights, and backyard memories ahead.", maxLength: 100 },
    ],
  },
  {
    id: "season-fall",
    name: "First Day of Fall",
    pillar: "Seasonal",
    description: "Welcome autumn with cozy, warm tones. Great for neighborhood content.",
    width: 1080,
    height: 1080,
    bgType: "photo-fullbleed",
    layout: "bottom-text",
    hasPhotoSlot: true,
    fields: [
      { id: "headline", label: "Headline", type: "headline", defaultValue: "Happy First Day of Fall", maxLength: 40 },
      { id: "body", label: "Message", type: "body", defaultValue: "Cozy vibes, changing leaves, and pumpkin everything.", maxLength: 100 },
    ],
  },
  {
    id: "season-winter",
    name: "First Day of Winter",
    pillar: "Seasonal",
    description: "Welcome winter with a warm, inviting feel. Perfect for holiday season.",
    width: 1080,
    height: 1080,
    bgType: "photo-fullbleed",
    layout: "bottom-text",
    hasPhotoSlot: true,
    fields: [
      { id: "headline", label: "Headline", type: "headline", defaultValue: "Happy First Day of Winter", maxLength: 40 },
      { id: "body", label: "Message", type: "body", defaultValue: "Snow, hot cocoa, and the warmth of home.", maxLength: 100 },
    ],
  },
];
