import { beforeEach, describe, expect, it, vi } from "vitest";
import { NextRequest } from "next/server";
import { POST } from "./route";

const routeMocks = vi.hoisted(() => ({
  generateGptImage: vi.fn(),
  isS3Configured: vi.fn(),
  uploadToS3: vi.fn(),
  photoAssetCreate: vi.fn(),
  withTenantDb: vi.fn(),
  resolveAccess: vi.fn(),
}));

vi.mock("@/lib/api-auth", () => ({
  requireAuthContext: vi.fn(async () => ({
    userId: "user-1",
    tenantId: "tenant-1",
    organizationId: "tenant-1",
    role: "owner",
    isSuperadmin: false,
  })),
}));

vi.mock("@/lib/rate-limit", () => ({
  rateLimit: vi.fn(async () => true),
  buildRateLimitKey: vi.fn(() => "test-key"),
  RateLimitUnavailableError: class RateLimitUnavailableError extends Error {},
}));

vi.mock("@/lib/db", () => ({
  withTenantDb: routeMocks.withTenantDb,
}));

vi.mock("@/lib/authz", () => ({
  resolveAccess: routeMocks.resolveAccess,
}));

vi.mock("@/lib/studio/gpt-image", () => ({
  classifyGptFallbackReason: vi.fn(() => "provider_error"),
  generateGptImage: routeMocks.generateGptImage,
  gptImageConfigured: vi.fn(() => true),
}));

vi.mock("@/lib/storage", () => ({
  isS3Configured: routeMocks.isS3Configured,
  uploadToS3: routeMocks.uploadToS3,
}));

vi.mock("@/lib/studio/vision-image-input", () => ({
  referenceImageToGeminiInline: vi.fn(async () => null),
}));

const LISTING_PROMPT =
  "make an instagram post about my new listing 223 victor ct. in ballwin, mo 63021";

const TINY_JPEG = "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/2wBDAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQH/wAARCAABAAEDAREAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAb/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/9oADAMBEQCEAD8AXwD/2Q==";

function postGenerateImage(body: Record<string, unknown>) {
  return POST(
    new NextRequest("http://localhost/api/generate-image", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(body),
    }),
  );
}

describe("POST /api/generate-image", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    vi.stubEnv("GEMINI_API_KEY", "test-gemini-key");
    vi.stubEnv("OPENAI_API_KEY", "test-openai-key");
    routeMocks.isS3Configured.mockReturnValue(false);
    routeMocks.resolveAccess.mockResolvedValue({ hasAccess: true });
    routeMocks.photoAssetCreate.mockResolvedValue({ id: "photo-1" });
    routeMocks.withTenantDb.mockImplementation(
      async (_auth: unknown, fn: (tx: unknown) => Promise<unknown>) =>
        fn({
          organization: {
            findUnique: vi.fn(async () => ({ plan: "solo", brandEngine: null })),
          },
          photoAsset: {
            create: routeMocks.photoAssetCreate,
          },
        }),
    );
  });

  it("requires a readable reference when listingMode is set", async () => {
    const res = await postGenerateImage({
      prompt: "Professional listing exterior",
      listingMode: true,
      sourceIntent: LISTING_PROMPT,
    });
    const body = await res.json();

    expect(res.status).toBe(422);
    expect(body.error).toMatch(/property photo attached/i);
  });

  it("returns 422 when reference image cannot be loaded", async () => {
    const res = await postGenerateImage({
      prompt: "Enhance listing photo",
      referenceImage: TINY_JPEG,
      sourceIntent: LISTING_PROMPT,
      listingMode: true,
    });
    const body = await res.json();

    expect(res.status).toBe(422);
    expect(body.error).toMatch(/could not read your listing photo/i);
  });

  it("stores generated bytes server-side and returns a compact public URL", async () => {
    const rawBase64 = Buffer.from("generated-image-bytes").toString("base64");
    routeMocks.generateGptImage.mockResolvedValue({
      ok: true,
      imageDataUrl: `data:image/jpeg;base64,${rawBase64}`,
      rawBase64,
      mimeType: "image/jpeg",
      text: "",
      model: "gpt-image-test",
    });
    routeMocks.isS3Configured.mockReturnValue(true);
    routeMocks.uploadToS3.mockResolvedValue({
      url: "https://media.example.com/tenants/tenant-1/studio/generated.jpg",
      key: "tenants/tenant-1/studio/generated.jpg",
    });

    const res = await postGenerateImage({
      prompt: "Create a launch announcement",
      sourceIntent: "Restaurant Creatives launch announcement",
      composed: true,
      engine: "gpt",
      quality: "standard",
      locationId: "location-1",
    });
    const body = await res.json();

    expect(res.status).toBe(200);
    expect(body.image).toBe(
      "https://media.example.com/tenants/tenant-1/studio/generated.jpg",
    );
    expect(JSON.stringify(body).length).toBeLessThan(1_000);
    expect(routeMocks.uploadToS3).toHaveBeenCalledWith(
      expect.objectContaining({
        key: expect.stringMatching(/^tenants\/tenant-1\/studio\/.+\.jpg$/),
        contentType: "image/jpeg",
      }),
    );
    const uploaded = routeMocks.uploadToS3.mock.calls[0]?.[0];
    expect(Buffer.isBuffer(uploaded.body)).toBe(true);
    expect(uploaded.body.equals(Buffer.from("generated-image-bytes"))).toBe(true);
    expect(routeMocks.photoAssetCreate).toHaveBeenCalledTimes(1);
    expect(routeMocks.photoAssetCreate).toHaveBeenCalledWith({
      data: expect.objectContaining({
        organizationId: "tenant-1",
        locationId: "location-1",
        url: body.image,
        mimeType: "image/jpeg",
      }),
    });
    expect(routeMocks.generateGptImage).toHaveBeenCalledWith(
      expect.objectContaining({
        quality: "standard",
        action: "generate",
        preferDirectImagesApi: true,
      }),
    );
  });

  it("passes Draft through to GPT without requiring the High entitlement", async () => {
    const rawBase64 = Buffer.from("draft-image").toString("base64");
    routeMocks.generateGptImage.mockResolvedValue({
      ok: true,
      imageDataUrl: `data:image/jpeg;base64,${rawBase64}`,
      rawBase64,
      mimeType: "image/jpeg",
      text: "",
      model: "gpt-image-test",
    });

    const res = await postGenerateImage({
      prompt: "Create a quick layout draft",
      composed: true,
      engine: "gpt",
      quality: "draft",
    });

    expect(res.status).toBe(200);
    expect(routeMocks.generateGptImage).toHaveBeenCalledWith(
      expect.objectContaining({
        quality: "draft",
        preferDirectImagesApi: true,
      }),
    );
    expect(routeMocks.withTenantDb).not.toHaveBeenCalled();
  });

  it("refuses an oversized inline response when durable storage is unavailable", async () => {
    const rawBase64 = Buffer.alloc(3_100_000, 7).toString("base64");
    routeMocks.generateGptImage.mockResolvedValue({
      ok: true,
      imageDataUrl: `data:image/jpeg;base64,${rawBase64}`,
      rawBase64,
      mimeType: "image/jpeg",
      text: "",
      model: "gpt-image-test",
    });

    const res = await postGenerateImage({
      prompt: "Create a detailed launch announcement",
      composed: true,
      engine: "gpt",
      quality: "standard",
    });
    const body = await res.json();

    expect(res.status).toBe(502);
    expect(body.code).toBe("GENERATED_IMAGE_DELIVERY_FAILED");
    expect(JSON.stringify(body).length).toBeLessThan(500);
    expect(routeMocks.uploadToS3).not.toHaveBeenCalled();
  });
});
